### ISSUE TITLE
Error when running `pod install` with plugin

### ISSUE THREAD

**Issue by colinhumber** [CocoaPods/cocoapods-acknowledgements#18]
I'm running CocoaPods 0.39 and included the plugin in my Podfile, but I get the following error when doing a `pod install`. My Podfile is setup as follows:

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
plugin 'cocoapods-acknowledgements', :settings_bundle => true

# Pods here
```

```bash
---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- cocoapods_acknowledgements
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-acknowledgements` be installed. Please install it and try installation again.
```

I've checked the plugin path and the plugin is properly installed there.

**Comment by orta** [comment]
Sounds like time for a patch release :dancers:

**Comment by colinhumber** [comment]
:heart:

**Comment by orta** [comment]
Hrm, interestingly, I can't reproduce this :-/

**Comment by colinhumber** [comment]
Lemme try in a fresh project, see if it's just something messed up there.

**Comment by colinhumber** [comment]
Pretty sure it's something in my environment and permissions. Gonna run some tests and post my results in a little bit.

**Comment by colinhumber** [comment]
Looks like it was an environment issue. I reworked my rvm setup and it's working fine now!

**Comment by orta** [comment]
:+1:  cool beans, if this comes back up feel free to re-open.

**Comment by masaniemi** [comment]
I had the exact same problem, and the reason was that several files in /Library/Ruby/Gems/2.0.0/gems/cocoapods-acknowledgements-1.0.0/ and its subdirectories had too strict access permissions (600). Setting 644 permissions to these files fixed the problem.

**Comment by cesarbars** [comment]
I had the same issue and the fix used by @masaniemi also worked here.

**Comment by r4n4newpage** [comment]
Having the same :) 
`[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] [!] Your Podfile requires that the plugin `cocoapods-acknowledgements` be installed. Please install it and try installation again.`
