### ISSUE TITLE
RuntimeError - Cannot write  to an ascii plist

### ISSUE THREAD

**Issue by CognitiveDisson** [CocoaPods/cocoapods-acknowledgements#40]
I get following errors when i try ```pod install```.

```
RuntimeError - Cannot write  to an ascii plist
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:63:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:29:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:128:in `write_dictionary_key_value_pair'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:108:in `write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:29:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:97:in `write_array_element'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:91:in `block in write_array'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:90:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:90:in `write_array'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:80:in `write_array'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:53:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:29:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:128:in `write_dictionary_key_value_pair'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:119:in `block in write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:118:in `write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:108:in `write_dictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer.rb:55:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:29:in `write_object'
/usr/local/lib/ruby/gems/2.2.0/gems/nanaimo-0.1.2/lib/nanaimo/writer/xml.rb:13:in `write'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:55:in `block in write_to_path'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:53:in `open'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:53:in `write_to_path'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:7:in `save_metadata'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:71:in `block (4 levels) in <module:CocoaPodsAcknowledgements>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:63:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:63:in `block (3 levels) in <module:CocoaPodsAcknowledgements>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:60:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:60:in `block (2 levels) in <module:CocoaPodsAcknowledgements>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-acknowledgements-1.1.2/lib/cocoapods_acknowledgements.rb:52:in `block in <module:CocoaPodsAcknowledgements>'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:109:in `call'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:101:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/hooks_manager.rb:100:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:493:in `run_plugins_post_install_hooks'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:472:in `perform_post_install_actions'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:121:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Cocoapods version:
```
pod --version
1.1.1
```
On 0.39.0 version all work correct.

**Comment by segiddins** [comment]
`gem install xcodeproj:1.4.1`
