### ISSUE TITLE
Unable to run pod install on an M1 Mac

### ISSUE THREAD

**Issue by kevinchau** [CocoaPods/cocoapods-acknowledgements#62]
have tried various permutations of running rosetta terminal and with the `arch-x86_64` flag.

Always comes down to this:

`Error loading the plugin `cocoapods-acknowledgements-1.3.0`.

LoadError - dlsym(0x7f7fcc589e10, Init_redcarpet): symbol not found - /Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/redcarpet-3.5.0/lib/redcarpet.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements/plist_generator.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements.rb:2:in `<module:CocoaPodsAcknowledgements>'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `each'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
`

**Comment by mcichecki** [comment]
@kevinchau did you manage to resolve this issue? It's been 5 months and this issue is still present. I tried running terminal under Rosetta but it didn't help.

**Comment by kevinchau** [comment]
I’m able to get it to run with ‘arch -x86_64’, but running with Rosetta and native do not work.

**Comment by mcichecki** [comment]
@kevinchau so you just open the Terminal not running Rosetta (arm64 arch) and run `arch -x86_64 pod install` with `plugin 'cocoapods-acknowledgments'` in your Podfile and it works? I tried this setting as well but error still persists.

**Comment by kevinchau** [comment]
Yes. What errors are you getting?

**Comment by mcichecki** [comment]
`Error loading the plugin` and info about the wrong architecture for redcarpet. Full log:

```
~/dev/iOS/other/acknowledgments-test ❯ arch -x86_64 pod install                                                                       15:02:47

---------------------------------------------
Error loading the plugin `cocoapods-acknowledgements-1.3.0`.

LoadError - dlopen(/Users/test/.gems/gems/redcarpet-3.5.1/lib/redcarpet.bundle, 9): no suitable image found.  Did find:
	/Users/test/.gems/gems/redcarpet-3.5.1/lib/redcarpet.bundle: mach-o, but wrong architecture
	/Users/test/.gems/gems/redcarpet-3.5.1/lib/redcarpet.bundle: mach-o, but wrong architecture - /Users/test/.gems/gems/redcarpet-3.5.1/lib/redcarpet.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/test/.gems/gems/redcarpet-3.5.1/lib/redcarpet.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/test/.gems/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements/plist_generator.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/test/.gems/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements.rb:2:in `<module:CocoaPodsAcknowledgements>'
/Users/test/.gems/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_acknowledgements.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/test/.gems/gems/cocoapods-acknowledgements-1.3.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `block in safe_activate_and_require'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `each'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Users/test/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

[!] Your Podfile requires that the plugin `cocoapods-acknowledgments` be installed. Please install it and try installation again.
```

Of course I've already installed the `cocoapods-acknowlegments` (`Successfully installed cocoapods-acknowledgements-1.3.0`)

**Comment by kevinchau** [comment]
I don’t remember what I did exactly, but there was a lot of uninstalling cocoa pods and reinstalling, with combinations of using the arch flag and running native.

**Comment by ameshf** [comment]
I'm getting the same error as @mcichecki 
Any way to solve this?

**Comment by HithakshiK** [comment]
I was able to solve this issue using below solution
Issue:
https://github.com/orta/cocoapods-keys/issues/217

Solution: 
https://github.com/orta/cocoapods-keys/issues/217#issuecomment-1005712448

hope it helps someone.

**Comment by snoozemoose** [comment]
I was able to work around the whole problem by removing dependency to `redcarpet` from `cocoapods-acknowlegments`. This was easy since `redcarpet` is only used in a single place. Instead, my fork of `cocoapods-acknowlegments` is now using `kramdown` (https://github.com/gettalong/kramdown).
